### ISSUE TITLE
Watering level feature request

### ISSUE THREAD

**Issue by jchiar** [drsprite/OpenSprinkler-Push-Notifications#1]
Didn't know where to add this, so i put it here.

Some addition like this:

```
    def getWaterLevel():
try:
    ospiWaterLevel = urllib2.urlopen("http://localhost:" + ospiPort + "/jo?pw=" + ospiApiPasswordHash).read()
except:
    syslog.syslog("Unable to load the OSPi API URL for Water Level. You might have a bad hashed password.")
    sendEmail()


     try:
    data = json.loads(ospiWaterLevel)
except:
    syslog.syslog("Unable to parse OSPi Water Level JSON Output.")
    sendEmail()

waterlevel = data["wl"]
#print "Getting water level" % (data["wl"])
return waterlevel`
```

But I could have that code all wrong,lol.

**Comment by poblabs** [comment]
I like it! I'll add it in later today or tomorrow

**Comment by jchiar** [comment]
Was my code close? New to Python..

**Comment by poblabs** [comment]
I haven't implemented it yet, but it looks like a clone of the other check functions so it should be pretty close. Just need to add it into the main loop. 

I'm also updating the config file for notifications on/off for all these little checks so there's some flexibility in getting notifications for what people care about. (For example, some people may not care about rain sensor, or water levels, etc.). Once I get that down, I'll hook this in and try it out! Hopefully by the end of the weekend.

**Comment by poblabs** [comment]
Your code was mostly there. The print debug was wrong, but I fixed it. I also added in the check loop in the main loop in addition to some options for enable/disable this check and customizing the notification message. Check it out!

**Comment by jchiar** [comment]
Great update!
