### ISSUE TITLE
No more notification

### ISSUE THREAD

**Issue by bolfox** [drsprite/OpenSprinkler-Push-Notifications#6]
Hi,
suddenly my opsi doesn’t send push anymore.

Nothing chances.

Connection is ok, Weather is updated, Pushover setting are correct, pushover is working...

Any ideas?

**Comment by poblabs** [comment]
I'm not sure, to be honest. I do not use Pushover. Has Pushover changed their code? Are they having problems?

@AcceleratingVector added the [Pushover code](https://github.com/poblabs/OpenSprinkler-Push-Notifications/pull/2). @AcceleratingVector, are you still using this script and is it still working with Pushover (assuming you still use Pushover if using this notification script)?

Edit: AcceleratingVector added the sound option for Pushover. I must have used Pushover at one point - but I don't use it anymore.

**Comment by oldjohngalt** [comment]
I am still using PushOver and am still getting notifications without issue.

**Comment by bolfox** [comment]
Tnx to all, i have found the problem, the Weather station that i was using is no more active, this was blokking all... Changing the location fix the problem...
